// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using url_shortener.Data.Contexts.Default;

#nullable disable

namespace url_shortener.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20250722213715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("url_shortener.Domain.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID_LINK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DS_ORIGINAL_URL");

                    b.Property<string>("ShortenedUrl")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DS_SHORTENED_URL");

                    b.HasKey("Id");

                    b.ToTable("TB_LINK", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
